version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:eu-central-1:666234783044:task-definition/aws-microservice:4
        LoadBalancerInfo:
          ContainerName: "sample-website"
          ContainerPort: 5000